//Category
export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';
export const CREATE_CATEGORY_RESET = 'CREATE_CATEGORY_RESET';

export const GET_ALL_CATEGORY_REQUEST = 'GET_ALL_CATEGORY_REQUEST';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAIL = 'GET_ALL_CATEGORY_FAIL';
export const GET_ALL_CATEGORY_RESET = 'GET_ALL_CATEGORY_RESET';

export const EDIT_CATEGORY_REQUEST = 'EDIT_CATEGORY_REQUEST';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAIL = 'EDIT_CATEGORY_FAIL';
export const EDIT_CATEGORY_RESET = 'EDIT_CATEGORY_RESET';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';
export const DELETE_CATEGORY_RESET = 'DELETE_CATEGORY_RESET';

// Sub-category
export const CREATE_SUB_CATEGORY_REQUEST = 'CREATE_SUB_CATEGORY_REQUEST';
export const CREATE_SUB_CATEGORY_SUCCESS = 'CREATE_SUB_CATEGORY_SUCCESS';
export const CREATE_SUB_CATEGORY_FAIL = 'CREATE_SUB_CATEGORY_FAIL';
export const CREATE_SUB_CATEGORY_RESET = 'CREATE_SUB_CATEGORY_RESET';

export const GET_ALL_SUB_CATEGORY_REQUEST = 'GET_ALL_SUB_CATEGORY_REQUEST';
export const GET_ALL_SUB_CATEGORY_SUCCESS = 'GET_ALL_SUB_CATEGORY_SUCCESS';
export const GET_ALL_SUB_CATEGORY_FAIL = 'GET_ALL_SUB_CATEGORY_FAIL';
export const GET_ALL_SUB_CATEGORY_RESET = 'GET_ALL_SUB_CATEGORY_RESET';

export const EDIT_SUB_CATEGORY_REQUEST = 'EDIT_SUB_CATEGORY_REQUEST';
export const EDIT_SUB_CATEGORY_SUCCESS = 'EDIT_SUB_CATEGORY_SUCCESS';
export const EDIT_SUB_CATEGORY_FAIL = 'EDIT_SUB_CATEGORY_FAIL';
export const EDIT_SUB_CATEGORY_RESET = 'EDIT_SUB_CATEGORY_RESET';

export const DELETE_SUB_CATEGORY_REQUEST = 'DELETE_SUB_CATEGORY_REQUEST';
export const DELETE_SUB_CATEGORY_SUCCESS = 'DELETE_SUB_CATEGORY_SUCCESS';
export const DELETE_SUB_CATEGORY_FAIL = 'DELETE_SUB_CATEGORY_FAIL';
export const DELETE_SUB_CATEGORY_RESET = 'DELETE_SUB_CATEGORY_RESET';

// Child-Category
export const CREATE_CHILD_CATEGORY_REQUEST = 'CREATE_CHILD_CATEGORY_REQUEST';
export const CREATE_CHILD_CATEGORY_SUCCESS = 'CREATE_CHILD_CATEGORY_SUCCESS';
export const CREATE_CHILD_CATEGORY_FAIL = 'CREATE_CHILD_CATEGORY_FAIL';
export const CREATE_CHILD_CATEGORY_RESET = 'CREATE_CHILD_CATEGORY_RESET';

export const GET_ALL_CHILD_CATEGORY_REQUEST = 'GET_ALL_CHILD_CATEGORY_REQUEST';
export const GET_ALL_CHILD_CATEGORY_SUCCESS = 'GET_ALL_CHILD_CATEGORY_SUCCESS';
export const GET_ALL_CHILD_CATEGORY_FAIL = 'GET_ALL_CHILD_CATEGORY_FAIL';
export const GET_ALL_CHILD_CATEGORY_RESET = 'GET_ALL_CHILD_CATEGORY_RESET';

export const EDIT_CHILD_CATEGORY_REQUEST = 'EDIT_CHILD_CATEGORY_REQUEST';
export const EDIT_CHILD_CATEGORY_SUCCESS = 'EDIT_CHILD_CATEGORY_SUCCESS';
export const EDIT_CHILD_CATEGORY_FAIL = 'EDIT_CHILD_CATEGORY_FAIL';
export const EDIT_CHILD_CATEGORY_RESET = 'EDIT_CHILD_CATEGORY_RESET';

export const DELETE_CHILD_CATEGORY_REQUEST = 'DELETE_CHILD_CATEGORY_REQUEST';
export const DELETE_CHILD_CATEGORY_SUCCESS = 'DELETE_CHILD_CATEGORY_SUCCESS';
export const DELETE_CHILD_CATEGORY_FAIL = 'DELETE_CHILD_CATEGORY_FAIL';
export const DELETE_CHILD_CATEGORY_RESET = 'DELETE_CHILD_CATEGORY_RESET';

// Get Sub Category under main Catgeory ID
export const GET_SUBCAT_OF_MAINCAT_REQUEST = 'GET_SUBCAT_OF_MAINCAT_REQUEST';
export const GET_SUBCAT_OF_MAINCAT_SUCCESS = 'GET_SUBCAT_OF_MAINCAT_SUCCESS';
export const GET_SUBCAT_OF_MAINCAT_FAIL = 'GET_SUBCAT_OF_MAINCAT_FAIL';
export const GET_SUBCAT_OF_MAINCAT_RESET = 'GET_SUBCAT_OF_MAINCAT_RESET';

export const GET_CHILDCAT_OF_SUBCAT_REQUEST = 'GET_CHILDCAT_OF_SUBCAT_REQUEST';
export const GET_CHILDCAT_OF_SUBCAT_SUCCESS = 'GET_CHILDCAT_OF_SUBCAT_SUCCESS';
export const GET_CHILDCAT_OF_SUBCAT_FAIL = 'GET_CHILDCAT_OF_SUBCAT_FAIL';
export const GET_CHILDCAT_OF_SUBCAT_RESET = 'GET_CHILDCAT_OF_SUBCAT_RESET';

// Get Single Category ID
export const GET_ID_SINGLE_CATEGORY_REQUEST = 'GET_ID_SINGLE_CATEGORY_REQUEST';
export const GET_ID_SINGLE_CATEGORY_SUCCESS = 'GET_ID_SINGLE_CATEGORY_SUCCESS';
export const GET_ID_SINGLE_CATEGORY_FAIL = 'GET_ID_SINGLE_CATEGORY_FAIL';
export const GET_ID_SINGLE_CATEGORY_RESET = 'GET_ID_SINGLE_CATEGORY_RESET';

// Get Single Sub-Category ID
export const GET_ID_SINGLE_SUB_CATEGORY_REQUEST =
  'GET_ID_SINGLE_CATEGORY_REQUEST';
export const GET_ID_SINGLE_SUB_CATEGORY_SUCCESS =
  'GET_ID_SINGLE_SUB_CATEGORY_SUCCESS';
export const GET_ID_SINGLE_SUB_CATEGORY_FAIL =
  'GET_ID_SINGLE_SUB_CATEGORY_FAIL';
export const GET_ID_SINGLE_SUB_CATEGORY_RESET =
  'GET_ID_SINGLE_SUB_CATEGORY_RESET';

// Get Single Child-Category ID
export const GET_ID_SINGLE_CHILD_CATEGORY_REQUEST =
  'GET_ID_SINGLE_CATEGORY_REQUEST';
export const GET_ID_SINGLE_CHILD_CATEGORY_SUCCESS =
  'GET_ID_SINGLE_CHILD_CATEGORY_SUCCESS';
export const GET_ID_SINGLE_CHILD_CATEGORY_FAIL =
  'GET_ID_SINGLE_CHILD_CATEGORY_FAIL';
export const GET_ID_SINGLE_CHILD_CATEGORY_RESET =
  'GET_ID_SINGLE_CHILD_CATEGORY_RESET';
